### ISSUE TITLE
mqtt support

### ISSUE THREAD

**Issue by lclem** [bertrik/ttn-gateway-collector#3]
would it be possible to publish the collected data to a user-specified mqtt server & topic?

**Comment by bertrik** [comment]
Yes, I think that would be possible.

With respect to the mqtt server and topic, the application can currently collect data from multiple gateways (say the gateways in your local community), I think I would make sense then to make the gateway id part of the destination mqtt topic.

With respect to the mqtt payload, I think the application could just forward the exact JSON as collected from TTN, without the 'result' wrapper, like https://github.com/bertrik/ttn-gateway-collector/blob/master/ttn-gateway-collector/src/test/resources/unconfirmed.json

**Comment by bertrik** [comment]
I just added initial support for it, you can specify an MQTT server, an uplink topic and a downlink topic. Maybe I'll also make a gateway status topic.
